version: 2

models: 
  - name: customers
    description: Each row represents a customer
    columns:
      - name: customer_id
        description: The Primary Key for the customer
        tests:
          - not_null
          - unique

  - name: monthly_customers
    description: Each row represents a month, with number of customers who placed their first order
    columns:
      - name: month_date
        description: The first day of the month
        tests:
          - unique
      - name: total_customers
        description: The total number of customers who placed their first order for the month
