version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club
    # Remove for now.
    # freshness:
    #   error_after:
    #     count: 12
    #     period: hour
    # loaded_at_field: created_at
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
      
      - name: order_items
        columns:
          - name: id
            tests:
              - not_null

      - name: product_prices
        columns:
          - name: id
            tests:
              - unique
              - not_null
      
      - name: products
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: category
            tests:
              - accepted_values:
                  values: ['coffee beans', 'brewing supplies', 'merch']
                  config:
                    severity: warn
                    
  - name: web_tracking
    project: analytics-engineers-club
    tables:
      - name: pageviews
        columns:
          - name: id
            tests:
              - unique
              - not_null
      
